# Dataset & API
api_dataset: h01_c2                  
cave_client_name: h01_c3_flat
image_layer_source: "precomputed://gs://h01-release/data/20210601/4nm_raw"
segmentation_layer_source: "precomputed://gs://h01-release/data/20210601/c2"

# S3 upload parameters
aws_secret_name: ''                  
bucket: neurd-datalake              
s3_base_path: h01_autoproof_precomputed_meshes

# Meshes to upload
segment_ids:
  - 329209033

# Viewer defaults
viewer_dimensions: [8, 8, 30]
image_layer_name:  "4nm_em_image"
segmentation_layer_name:  "c2_flat_segmentation"
raw_layer_name: "raw"
proofread_layer_name: "proofread"

# Volume‑info parameters (used to generate the `info` JSON)
num_channels: 1
resolution: [8, 8, 30]
chunk_sizes:
  - [64, 64, 64]
size: [1, 1, 1]